Fix for exception at os-get
Due to the usage of an undefined method name, the following exception was thrown when
using the os-get node (here: with IBM BLuemix):
ERR Unhandled rejection TypeError: os.downloadFileFromContainer is not a function
ERR     at /home/vcap/app/node_modules/node-red-contrib-objectstore/objstore.js:136:30